### ISSUE TITLE
Slow missing chunks

### ISSUE THREAD

**Issue by fireduck64** [snowblossomcoin/channels#2]
Investigate possible causes and fix chunk downloading.  It should almost always be instant.

**Comment by fireduck64** [comment]
"ChannelChunkGetter" #86 daemon prio=6 os_prio=0 tid=0x00007fa1b8151000 nid=0x63c8 in Object.wait() [0x00007fa13c568000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at duckutil.PeriodicThread.run(PeriodicThread.java:46)
        - locked <0x00000007240a8d30> (a java.lang.Object)
